/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAdminCodesRouteImport } from './routes/_authenticated/admin-codes'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin-users'
import { Route as AuthenticatedBucketRouteImport } from './routes/_authenticated/bucket'
import { Route as AuthenticatedBudgetRouteImport } from './routes/_authenticated/budget'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedCommitmentsRouteImport } from './routes/_authenticated/commitments'
import { Route as AuthenticatedCooldownRouteImport } from './routes/_authenticated/cooldown'
import { Route as AuthenticatedDiaryRouteImport } from './routes/_authenticated/diary'
import { Route as AuthenticatedFoodRouteImport } from './routes/_authenticated/food'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/map'
import { Route as AuthenticatedMemoryBookRouteImport } from './routes/_authenticated/memory-book'
import { Route as AuthenticatedMoreRouteImport } from './routes/_authenticated/more'
import { Route as AuthenticatedNestRouteImport } from './routes/_authenticated/nest'
import { Route as AuthenticatedPeriodRouteImport } from './routes/_authenticated/period'
import { Route as AuthenticatedPhotosRouteImport } from './routes/_authenticated/photos'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedQuestionsRouteImport } from './routes/_authenticated/questions'
import { Route as AuthenticatedSpicyRouteImport } from './routes/_authenticated/spicy'
import { Route as AuthenticatedTodosRouteImport } from './routes/_authenticated/todos'
import { Route as AuthenticatedWellbeingRouteImport } from './routes/_authenticated/wellbeing'
import { Route as AuthenticatedGamesIndexRouteImport } from './routes/_authenticated/games.index'
import { Route as AuthenticatedGamesKindRouteImport } from './routes/_authenticated/games.$kind'
import { Route as AuthenticatedGamesArcadeRouteImport } from './routes/_authenticated/games.arcade'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminCodesRoute = AuthenticatedAdminCodesRouteImport.update({
  id: '/admin-codes',
  path: '/admin-codes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin-users',
  path: '/admin-users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBucketRoute = AuthenticatedBucketRouteImport.update({
  id: '/bucket',
  path: '/bucket',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBudgetRoute = AuthenticatedBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommitmentsRoute =
  AuthenticatedCommitmentsRouteImport.update({
    id: '/commitments',
    path: '/commitments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCooldownRoute = AuthenticatedCooldownRouteImport.update({
  id: '/cooldown',
  path: '/cooldown',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiaryRoute = AuthenticatedDiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFoodRoute = AuthenticatedFoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMemoryBookRoute = AuthenticatedMemoryBookRouteImport.update({
  id: '/memory-book',
  path: '/memory-book',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMoreRoute = AuthenticatedMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNestRoute = AuthenticatedNestRouteImport.update({
  id: '/nest',
  path: '/nest',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPeriodRoute = AuthenticatedPeriodRouteImport.update({
  id: '/period',
  path: '/period',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPhotosRoute = AuthenticatedPhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuestionsRoute = AuthenticatedQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSpicyRoute = AuthenticatedSpicyRouteImport.update({
  id: '/spicy',
  path: '/spicy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTodosRoute = AuthenticatedTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWellbeingRoute = AuthenticatedWellbeingRouteImport.update({
  id: '/wellbeing',
  path: '/wellbeing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGamesIndexRoute = AuthenticatedGamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGamesKindRoute = AuthenticatedGamesKindRouteImport.update({
  id: '/games/$kind',
  path: '/games/$kind',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGamesArcadeRoute =
  AuthenticatedGamesArcadeRouteImport.update({
    id: '/games/arcade',
    path: '/games/arcade',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin-codes': typeof AuthenticatedAdminCodesRoute
  '/admin-users': typeof AuthenticatedAdminUsersRoute
  '/bucket': typeof AuthenticatedBucketRoute
  '/budget': typeof AuthenticatedBudgetRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/chat': typeof AuthenticatedChatRoute
  '/commitments': typeof AuthenticatedCommitmentsRoute
  '/cooldown': typeof AuthenticatedCooldownRoute
  '/diary': typeof AuthenticatedDiaryRoute
  '/food': typeof AuthenticatedFoodRoute
  '/map': typeof AuthenticatedMapRoute
  '/memory-book': typeof AuthenticatedMemoryBookRoute
  '/more': typeof AuthenticatedMoreRoute
  '/nest': typeof AuthenticatedNestRoute
  '/period': typeof AuthenticatedPeriodRoute
  '/photos': typeof AuthenticatedPhotosRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/questions': typeof AuthenticatedQuestionsRoute
  '/spicy': typeof AuthenticatedSpicyRoute
  '/todos': typeof AuthenticatedTodosRoute
  '/wellbeing': typeof AuthenticatedWellbeingRoute
  '/games/$kind': typeof AuthenticatedGamesKindRoute
  '/games/arcade': typeof AuthenticatedGamesArcadeRoute
  '/games/': typeof AuthenticatedGamesIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin-codes': typeof AuthenticatedAdminCodesRoute
  '/admin-users': typeof AuthenticatedAdminUsersRoute
  '/bucket': typeof AuthenticatedBucketRoute
  '/budget': typeof AuthenticatedBudgetRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/chat': typeof AuthenticatedChatRoute
  '/commitments': typeof AuthenticatedCommitmentsRoute
  '/cooldown': typeof AuthenticatedCooldownRoute
  '/diary': typeof AuthenticatedDiaryRoute
  '/food': typeof AuthenticatedFoodRoute
  '/map': typeof AuthenticatedMapRoute
  '/memory-book': typeof AuthenticatedMemoryBookRoute
  '/more': typeof AuthenticatedMoreRoute
  '/nest': typeof AuthenticatedNestRoute
  '/period': typeof AuthenticatedPeriodRoute
  '/photos': typeof AuthenticatedPhotosRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/questions': typeof AuthenticatedQuestionsRoute
  '/spicy': typeof AuthenticatedSpicyRoute
  '/todos': typeof AuthenticatedTodosRoute
  '/wellbeing': typeof AuthenticatedWellbeingRoute
  '/': typeof AuthenticatedIndexRoute
  '/games/$kind': typeof AuthenticatedGamesKindRoute
  '/games/arcade': typeof AuthenticatedGamesArcadeRoute
  '/games': typeof AuthenticatedGamesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin-codes': typeof AuthenticatedAdminCodesRoute
  '/_authenticated/admin-users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/bucket': typeof AuthenticatedBucketRoute
  '/_authenticated/budget': typeof AuthenticatedBudgetRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/commitments': typeof AuthenticatedCommitmentsRoute
  '/_authenticated/cooldown': typeof AuthenticatedCooldownRoute
  '/_authenticated/diary': typeof AuthenticatedDiaryRoute
  '/_authenticated/food': typeof AuthenticatedFoodRoute
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/memory-book': typeof AuthenticatedMemoryBookRoute
  '/_authenticated/more': typeof AuthenticatedMoreRoute
  '/_authenticated/nest': typeof AuthenticatedNestRoute
  '/_authenticated/period': typeof AuthenticatedPeriodRoute
  '/_authenticated/photos': typeof AuthenticatedPhotosRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/questions': typeof AuthenticatedQuestionsRoute
  '/_authenticated/spicy': typeof AuthenticatedSpicyRoute
  '/_authenticated/todos': typeof AuthenticatedTodosRoute
  '/_authenticated/wellbeing': typeof AuthenticatedWellbeingRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/games/$kind': typeof AuthenticatedGamesKindRoute
  '/_authenticated/games/arcade': typeof AuthenticatedGamesArcadeRoute
  '/_authenticated/games/': typeof AuthenticatedGamesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin-codes'
    | '/admin-users'
    | '/bucket'
    | '/budget'
    | '/calendar'
    | '/chat'
    | '/commitments'
    | '/cooldown'
    | '/diary'
    | '/food'
    | '/map'
    | '/memory-book'
    | '/more'
    | '/nest'
    | '/period'
    | '/photos'
    | '/profile'
    | '/questions'
    | '/spicy'
    | '/todos'
    | '/wellbeing'
    | '/games/$kind'
    | '/games/arcade'
    | '/games/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/reset-password'
    | '/admin-codes'
    | '/admin-users'
    | '/bucket'
    | '/budget'
    | '/calendar'
    | '/chat'
    | '/commitments'
    | '/cooldown'
    | '/diary'
    | '/food'
    | '/map'
    | '/memory-book'
    | '/more'
    | '/nest'
    | '/period'
    | '/photos'
    | '/profile'
    | '/questions'
    | '/spicy'
    | '/todos'
    | '/wellbeing'
    | '/'
    | '/games/$kind'
    | '/games/arcade'
    | '/games'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/admin-codes'
    | '/_authenticated/admin-users'
    | '/_authenticated/bucket'
    | '/_authenticated/budget'
    | '/_authenticated/calendar'
    | '/_authenticated/chat'
    | '/_authenticated/commitments'
    | '/_authenticated/cooldown'
    | '/_authenticated/diary'
    | '/_authenticated/food'
    | '/_authenticated/map'
    | '/_authenticated/memory-book'
    | '/_authenticated/more'
    | '/_authenticated/nest'
    | '/_authenticated/period'
    | '/_authenticated/photos'
    | '/_authenticated/profile'
    | '/_authenticated/questions'
    | '/_authenticated/spicy'
    | '/_authenticated/todos'
    | '/_authenticated/wellbeing'
    | '/_authenticated/'
    | '/_authenticated/games/$kind'
    | '/_authenticated/games/arcade'
    | '/_authenticated/games/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-codes': {
      id: '/_authenticated/admin-codes'
      path: '/admin-codes'
      fullPath: '/admin-codes'
      preLoaderRoute: typeof AuthenticatedAdminCodesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-users': {
      id: '/_authenticated/admin-users'
      path: '/admin-users'
      fullPath: '/admin-users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bucket': {
      id: '/_authenticated/bucket'
      path: '/bucket'
      fullPath: '/bucket'
      preLoaderRoute: typeof AuthenticatedBucketRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/budget': {
      id: '/_authenticated/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof AuthenticatedBudgetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commitments': {
      id: '/_authenticated/commitments'
      path: '/commitments'
      fullPath: '/commitments'
      preLoaderRoute: typeof AuthenticatedCommitmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cooldown': {
      id: '/_authenticated/cooldown'
      path: '/cooldown'
      fullPath: '/cooldown'
      preLoaderRoute: typeof AuthenticatedCooldownRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diary': {
      id: '/_authenticated/diary'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof AuthenticatedDiaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/food': {
      id: '/_authenticated/food'
      path: '/food'
      fullPath: '/food'
      preLoaderRoute: typeof AuthenticatedFoodRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/memory-book': {
      id: '/_authenticated/memory-book'
      path: '/memory-book'
      fullPath: '/memory-book'
      preLoaderRoute: typeof AuthenticatedMemoryBookRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/more': {
      id: '/_authenticated/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof AuthenticatedMoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nest': {
      id: '/_authenticated/nest'
      path: '/nest'
      fullPath: '/nest'
      preLoaderRoute: typeof AuthenticatedNestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/period': {
      id: '/_authenticated/period'
      path: '/period'
      fullPath: '/period'
      preLoaderRoute: typeof AuthenticatedPeriodRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/photos': {
      id: '/_authenticated/photos'
      path: '/photos'
      fullPath: '/photos'
      preLoaderRoute: typeof AuthenticatedPhotosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/questions': {
      id: '/_authenticated/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof AuthenticatedQuestionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/spicy': {
      id: '/_authenticated/spicy'
      path: '/spicy'
      fullPath: '/spicy'
      preLoaderRoute: typeof AuthenticatedSpicyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/todos': {
      id: '/_authenticated/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof AuthenticatedTodosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wellbeing': {
      id: '/_authenticated/wellbeing'
      path: '/wellbeing'
      fullPath: '/wellbeing'
      preLoaderRoute: typeof AuthenticatedWellbeingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/games/': {
      id: '/_authenticated/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof AuthenticatedGamesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/games/$kind': {
      id: '/_authenticated/games/$kind'
      path: '/games/$kind'
      fullPath: '/games/$kind'
      preLoaderRoute: typeof AuthenticatedGamesKindRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/games/arcade': {
      id: '/_authenticated/games/arcade'
      path: '/games/arcade'
      fullPath: '/games/arcade'
      preLoaderRoute: typeof AuthenticatedGamesArcadeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminCodesRoute: typeof AuthenticatedAdminCodesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedBucketRoute: typeof AuthenticatedBucketRoute
  AuthenticatedBudgetRoute: typeof AuthenticatedBudgetRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedCommitmentsRoute: typeof AuthenticatedCommitmentsRoute
  AuthenticatedCooldownRoute: typeof AuthenticatedCooldownRoute
  AuthenticatedDiaryRoute: typeof AuthenticatedDiaryRoute
  AuthenticatedFoodRoute: typeof AuthenticatedFoodRoute
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedMemoryBookRoute: typeof AuthenticatedMemoryBookRoute
  AuthenticatedMoreRoute: typeof AuthenticatedMoreRoute
  AuthenticatedNestRoute: typeof AuthenticatedNestRoute
  AuthenticatedPeriodRoute: typeof AuthenticatedPeriodRoute
  AuthenticatedPhotosRoute: typeof AuthenticatedPhotosRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedQuestionsRoute: typeof AuthenticatedQuestionsRoute
  AuthenticatedSpicyRoute: typeof AuthenticatedSpicyRoute
  AuthenticatedTodosRoute: typeof AuthenticatedTodosRoute
  AuthenticatedWellbeingRoute: typeof AuthenticatedWellbeingRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedGamesKindRoute: typeof AuthenticatedGamesKindRoute
  AuthenticatedGamesArcadeRoute: typeof AuthenticatedGamesArcadeRoute
  AuthenticatedGamesIndexRoute: typeof AuthenticatedGamesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminCodesRoute: AuthenticatedAdminCodesRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedBucketRoute: AuthenticatedBucketRoute,
  AuthenticatedBudgetRoute: AuthenticatedBudgetRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedCommitmentsRoute: AuthenticatedCommitmentsRoute,
  AuthenticatedCooldownRoute: AuthenticatedCooldownRoute,
  AuthenticatedDiaryRoute: AuthenticatedDiaryRoute,
  AuthenticatedFoodRoute: AuthenticatedFoodRoute,
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedMemoryBookRoute: AuthenticatedMemoryBookRoute,
  AuthenticatedMoreRoute: AuthenticatedMoreRoute,
  AuthenticatedNestRoute: AuthenticatedNestRoute,
  AuthenticatedPeriodRoute: AuthenticatedPeriodRoute,
  AuthenticatedPhotosRoute: AuthenticatedPhotosRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedQuestionsRoute: AuthenticatedQuestionsRoute,
  AuthenticatedSpicyRoute: AuthenticatedSpicyRoute,
  AuthenticatedTodosRoute: AuthenticatedTodosRoute,
  AuthenticatedWellbeingRoute: AuthenticatedWellbeingRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedGamesKindRoute: AuthenticatedGamesKindRoute,
  AuthenticatedGamesArcadeRoute: AuthenticatedGamesArcadeRoute,
  AuthenticatedGamesIndexRoute: AuthenticatedGamesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
